language: python
sudo: required

services:
  - docker

before_install:
  - cd certbot/
  - git fetch origin
  - git pull origin master
  - cd ..
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - cp ./Dockerfile certbot/Dockerfile

install:
  - docker build --rm --no-cache -t "$DOCKER_USERNAME"/certbot-rpi certbot/
  - docker push "$DOCKER_USERNAME"/certbot-rpi
  - docker tag "$DOCKER_USERNAME"/certbot-rpi "$DOCKER_USERNAME"/letsencrypt-rpi
  - docker push "$DOCKER_USERNAME"/letsencrypt-rpi

script: true
