language: python
sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - git remote add certbot https://github.com/certbot/certbot
  - git fetch certbot master
  - git read-tree --prefix=certbot/ -u certbot/master
  - cp ./Dockerfile certbot/Dockerfile

install:
  - docker build --rm --no-cache -t bcecchinato/certbot-rpi:build certbot/
  - VERSION=$(docker run -it --rm bcecchinato/certbot-rpi:build --version | cut -d" " -f2 | cut -d"." -f1-3)
  - docker tag bcecchinato/certbot-rpi:build bcecchinato/certbot-rpi:latest
  - docker tag bcecchinato/certbot-rpi:build bcecchinato/letsencrypt-rpi:latest
  - docker tag bcecchinato/certbot-rpi:build bcecchinato/certbot-rpi:$VERSION
  - docker tag bcecchinato/certbot-rpi:build bcecchinato/letsencrypt-rpi:$VERSION
  - docker push bcecchinato/certbot-rpi:latest
  - docker push bcecchinato/letsencrypt-rpi:latest
  - docker push bcecchinato/certbot-rpi:$VERSION
  - docker push bcecchinato/letsencrypt-rpi:$VERSION

script: true
